import type { Metadata } from "next";
import { Lato, Lora, Mulish } from "next/font/google";
import "./globals.css";

const lato = Lato({
  subsets: ["latin"],
  style: ["italic", "normal"],
  weight: ["100", "300", "400", "700", "900"],
});

const lora = Lora({
  subsets: ["latin"],
  style: ["italic", "normal"],
  weight: ["400", "500", "600", "700"],
});

const mulish = Mulish({
  subsets: ["latin"],
  style: ["italic", "normal"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  );
}
